// FIFA World Cup 2026 — sample tournament data (USA / Canada / Mexico)
// 48 teams across 12 groups of 4. All data is illustrative sample data.

function pts(t) {
  return t.won * 3 + t.drawn;
}
export function points(t) {
  return pts(t);
}
export function goalDiff(t) {
  return t.gf - t.ga;
}

// ---- Teams ------------------------------------------------------------
export const teams = [
  // Group A
  {
    id: "mex",
    name: "Mexico",
    code: "MEX",
    flag: "🇲🇽",
    group: "A",
    confederation: "CONCACAF",
    fifaRank: 14,
    played: 3,
    won: 2,
    drawn: 1,
    lost: 0,
    gf: 6,
    ga: 2,
  },
  {
    id: "ned",
    name: "Netherlands",
    code: "NED",
    flag: "🇳🇱",
    group: "A",
    confederation: "UEFA",
    fifaRank: 6,
    played: 3,
    won: 2,
    drawn: 0,
    lost: 1,
    gf: 7,
    ga: 3,
  },
  {
    id: "kor",
    name: "South Korea",
    code: "KOR",
    flag: "🇰🇷",
    group: "A",
    confederation: "AFC",
    fifaRank: 23,
    played: 3,
    won: 1,
    drawn: 1,
    lost: 1,
    gf: 4,
    ga: 4,
  },
  {
    id: "gha",
    name: "Ghana",
    code: "GHA",
    flag: "🇬🇭",
    group: "A",
    confederation: "CAF",
    fifaRank: 68,
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    gf: 2,
    ga: 10,
  },
  // Group B
  {
    id: "can",
    name: "Canada",
    code: "CAN",
    flag: "🇨🇦",
    group: "B",
    confederation: "CONCACAF",
    fifaRank: 43,
    played: 3,
    won: 2,
    drawn: 1,
    lost: 0,
    gf: 5,
    ga: 1,
  },
  {
    id: "bel",
    name: "Belgium",
    code: "BEL",
    flag: "🇧🇪",
    group: "B",
    confederation: "UEFA",
    fifaRank: 8,
    played: 3,
    won: 2,
    drawn: 0,
    lost: 1,
    gf: 6,
    ga: 3,
  },
  {
    id: "jpn",
    name: "Japan",
    code: "JPN",
    flag: "🇯🇵",
    group: "B",
    confederation: "AFC",
    fifaRank: 18,
    played: 3,
    won: 1,
    drawn: 1,
    lost: 1,
    gf: 5,
    ga: 4,
  },
  {
    id: "egy",
    name: "Egypt",
    code: "EGY",
    flag: "🇪🇬",
    group: "B",
    confederation: "CAF",
    fifaRank: 36,
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    gf: 1,
    ga: 9,
  },
  // Group C
  {
    id: "usa",
    name: "United States",
    code: "USA",
    flag: "🇺🇸",
    group: "C",
    confederation: "CONCACAF",
    fifaRank: 16,
    played: 3,
    won: 3,
    drawn: 0,
    lost: 0,
    gf: 8,
    ga: 2,
  },
  {
    id: "ger",
    name: "Germany",
    code: "GER",
    flag: "🇩🇪",
    group: "C",
    confederation: "UEFA",
    fifaRank: 10,
    played: 3,
    won: 2,
    drawn: 0,
    lost: 1,
    gf: 7,
    ga: 4,
  },
  {
    id: "mar",
    name: "Morocco",
    code: "MAR",
    flag: "🇲🇦",
    group: "C",
    confederation: "CAF",
    fifaRank: 12,
    played: 3,
    won: 1,
    drawn: 0,
    lost: 2,
    gf: 3,
    ga: 5,
  },
  {
    id: "uzb",
    name: "Uzbekistan",
    code: "UZB",
    flag: "🇺🇿",
    group: "C",
    confederation: "AFC",
    fifaRank: 57,
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    gf: 2,
    ga: 9,
  },
  // Group D
  {
    id: "arg",
    name: "Argentina",
    code: "ARG",
    flag: "🇦🇷",
    group: "D",
    confederation: "CONMEBOL",
    fifaRank: 1,
    played: 3,
    won: 3,
    drawn: 0,
    lost: 0,
    gf: 9,
    ga: 1,
  },
  {
    id: "cro",
    name: "Croatia",
    code: "CRO",
    flag: "🇭🇷",
    group: "D",
    confederation: "UEFA",
    fifaRank: 9,
    played: 3,
    won: 1,
    drawn: 1,
    lost: 1,
    gf: 4,
    ga: 4,
  },
  {
    id: "nga",
    name: "Nigeria",
    code: "NGA",
    flag: "🇳🇬",
    group: "D",
    confederation: "CAF",
    fifaRank: 41,
    played: 3,
    won: 1,
    drawn: 1,
    lost: 1,
    gf: 3,
    ga: 3,
  },
  {
    id: "sau",
    name: "Saudi Arabia",
    code: "KSA",
    flag: "🇸🇦",
    group: "D",
    confederation: "AFC",
    fifaRank: 58,
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    gf: 1,
    ga: 9,
  },
  // Group E
  {
    id: "fra",
    name: "France",
    code: "FRA",
    flag: "🇫🇷",
    group: "E",
    confederation: "UEFA",
    fifaRank: 2,
    played: 3,
    won: 2,
    drawn: 1,
    lost: 0,
    gf: 7,
    ga: 2,
  },
  {
    id: "sen",
    name: "Senegal",
    code: "SEN",
    flag: "🇸🇳",
    group: "E",
    confederation: "CAF",
    fifaRank: 17,
    played: 3,
    won: 2,
    drawn: 0,
    lost: 1,
    gf: 5,
    ga: 3,
  },
  {
    id: "aus",
    name: "Australia",
    code: "AUS",
    flag: "🇦🇺",
    group: "E",
    confederation: "AFC",
    fifaRank: 24,
    played: 3,
    won: 1,
    drawn: 1,
    lost: 1,
    gf: 3,
    ga: 4,
  },
  {
    id: "crc",
    name: "Costa Rica",
    code: "CRC",
    flag: "🇨🇷",
    group: "E",
    confederation: "CONCACAF",
    fifaRank: 52,
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    gf: 1,
    ga: 7,
  },
  // Group F
  {
    id: "bra",
    name: "Brazil",
    code: "BRA",
    flag: "🇧🇷",
    group: "F",
    confederation: "CONMEBOL",
    fifaRank: 3,
    played: 3,
    won: 2,
    drawn: 1,
    lost: 0,
    gf: 8,
    ga: 3,
  },
  {
    id: "por",
    name: "Portugal",
    code: "POR",
    flag: "🇵🇹",
    group: "F",
    confederation: "UEFA",
    fifaRank: 7,
    played: 3,
    won: 2,
    drawn: 1,
    lost: 0,
    gf: 7,
    ga: 2,
  },
  {
    id: "ivc",
    name: "Ivory Coast",
    code: "CIV",
    flag: "🇨🇮",
    group: "F",
    confederation: "CAF",
    fifaRank: 49,
    played: 3,
    won: 1,
    drawn: 0,
    lost: 2,
    gf: 3,
    ga: 6,
  },
  {
    id: "irn",
    name: "Iran",
    code: "IRN",
    flag: "🇮🇷",
    group: "F",
    confederation: "AFC",
    fifaRank: 20,
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    gf: 2,
    ga: 9,
  },
  // Group G
  {
    id: "eng",
    name: "England",
    code: "ENG",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    group: "G",
    confederation: "UEFA",
    fifaRank: 4,
    played: 3,
    won: 3,
    drawn: 0,
    lost: 0,
    gf: 8,
    ga: 1,
  },
  {
    id: "col",
    name: "Colombia",
    code: "COL",
    flag: "🇨🇴",
    group: "G",
    confederation: "CONMEBOL",
    fifaRank: 15,
    played: 3,
    won: 2,
    drawn: 0,
    lost: 1,
    gf: 5,
    ga: 3,
  },
  {
    id: "tun",
    name: "Tunisia",
    code: "TUN",
    flag: "🇹🇳",
    group: "G",
    confederation: "CAF",
    fifaRank: 45,
    played: 3,
    won: 1,
    drawn: 0,
    lost: 2,
    gf: 2,
    ga: 4,
  },
  {
    id: "qat",
    name: "Qatar",
    code: "QAT",
    flag: "🇶🇦",
    group: "G",
    confederation: "AFC",
    fifaRank: 38,
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    gf: 1,
    ga: 8,
  },
  // Group H
  {
    id: "esp",
    name: "Spain",
    code: "ESP",
    flag: "🇪🇸",
    group: "H",
    confederation: "UEFA",
    fifaRank: 5,
    played: 3,
    won: 3,
    drawn: 0,
    lost: 0,
    gf: 10,
    ga: 2,
  },
  {
    id: "uru",
    name: "Uruguay",
    code: "URU",
    flag: "🇺🇾",
    group: "H",
    confederation: "CONMEBOL",
    fifaRank: 11,
    played: 3,
    won: 1,
    drawn: 1,
    lost: 1,
    gf: 4,
    ga: 4,
  },
  {
    id: "cmr",
    name: "Cameroon",
    code: "CMR",
    flag: "🇨🇲",
    group: "H",
    confederation: "CAF",
    fifaRank: 53,
    played: 3,
    won: 1,
    drawn: 1,
    lost: 1,
    gf: 3,
    ga: 4,
  },
  {
    id: "jor",
    name: "Jordan",
    code: "JOR",
    flag: "🇯🇴",
    group: "H",
    confederation: "AFC",
    fifaRank: 64,
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    gf: 1,
    ga: 8,
  },
  // Group I
  {
    id: "ita",
    name: "Italy",
    code: "ITA",
    flag: "🇮🇹",
    group: "I",
    confederation: "UEFA",
    fifaRank: 13,
    played: 3,
    won: 2,
    drawn: 1,
    lost: 0,
    gf: 6,
    ga: 2,
  },
  {
    id: "ecu",
    name: "Ecuador",
    code: "ECU",
    flag: "🇪🇨",
    group: "I",
    confederation: "CONMEBOL",
    fifaRank: 28,
    played: 3,
    won: 2,
    drawn: 0,
    lost: 1,
    gf: 4,
    ga: 2,
  },
  {
    id: "rsa",
    name: "South Africa",
    code: "RSA",
    flag: "🇿🇦",
    group: "I",
    confederation: "CAF",
    fifaRank: 56,
    played: 3,
    won: 1,
    drawn: 1,
    lost: 1,
    gf: 3,
    ga: 4,
  },
  {
    id: "nzl",
    name: "New Zealand",
    code: "NZL",
    flag: "🇳🇿",
    group: "I",
    confederation: "OFC",
    fifaRank: 86,
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    gf: 1,
    ga: 6,
  },
  // Group J
  {
    id: "sui",
    name: "Switzerland",
    code: "SUI",
    flag: "🇨🇭",
    group: "J",
    confederation: "UEFA",
    fifaRank: 19,
    played: 3,
    won: 2,
    drawn: 1,
    lost: 0,
    gf: 5,
    ga: 2,
  },
  {
    id: "per",
    name: "Peru",
    code: "PER",
    flag: "🇵🇪",
    group: "J",
    confederation: "CONMEBOL",
    fifaRank: 32,
    played: 3,
    won: 2,
    drawn: 0,
    lost: 1,
    gf: 4,
    ga: 3,
  },
  {
    id: "alg",
    name: "Algeria",
    code: "ALG",
    flag: "🇩🇿",
    group: "J",
    confederation: "CAF",
    fifaRank: 39,
    played: 3,
    won: 1,
    drawn: 1,
    lost: 1,
    gf: 3,
    ga: 3,
  },
  {
    id: "irq",
    name: "Iraq",
    code: "IRQ",
    flag: "🇮🇶",
    group: "J",
    confederation: "AFC",
    fifaRank: 61,
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    gf: 1,
    ga: 5,
  },
  // Group K
  {
    id: "den",
    name: "Denmark",
    code: "DEN",
    flag: "🇩🇰",
    group: "K",
    confederation: "UEFA",
    fifaRank: 21,
    played: 3,
    won: 3,
    drawn: 0,
    lost: 0,
    gf: 7,
    ga: 2,
  },
  {
    id: "par",
    name: "Paraguay",
    code: "PAR",
    flag: "🇵🇾",
    group: "K",
    confederation: "CONMEBOL",
    fifaRank: 48,
    played: 3,
    won: 1,
    drawn: 1,
    lost: 1,
    gf: 3,
    ga: 3,
  },
  {
    id: "mli",
    name: "Mali",
    code: "MLI",
    flag: "🇲🇱",
    group: "K",
    confederation: "CAF",
    fifaRank: 51,
    played: 3,
    won: 1,
    drawn: 1,
    lost: 1,
    gf: 4,
    ga: 4,
  },
  {
    id: "pan",
    name: "Panama",
    code: "PAN",
    flag: "🇵🇦",
    group: "K",
    confederation: "CONCACAF",
    fifaRank: 42,
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    gf: 2,
    ga: 7,
  },
  // Group L
  {
    id: "ned2",
    name: "Austria",
    code: "AUT",
    flag: "🇦🇹",
    group: "L",
    confederation: "UEFA",
    fifaRank: 22,
    played: 3,
    won: 2,
    drawn: 1,
    lost: 0,
    gf: 6,
    ga: 3,
  },
  {
    id: "chi",
    name: "Chile",
    code: "CHI",
    flag: "🇨🇱",
    group: "L",
    confederation: "CONMEBOL",
    fifaRank: 44,
    played: 3,
    won: 2,
    drawn: 0,
    lost: 1,
    gf: 5,
    ga: 3,
  },
  {
    id: "tur",
    name: "Turkey",
    code: "TUR",
    flag: "🇹🇷",
    group: "L",
    confederation: "UEFA",
    fifaRank: 26,
    played: 3,
    won: 1,
    drawn: 1,
    lost: 1,
    gf: 4,
    ga: 4,
  },
  {
    id: "hon",
    name: "Honduras",
    code: "HON",
    flag: "🇭🇳",
    group: "L",
    confederation: "CONCACAF",
    fifaRank: 70,
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    gf: 1,
    ga: 6,
  },
];

export const teamMap = Object.fromEntries(teams.map((t) => [t.id, t]));

export const groups = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
];

export function standingsForGroup(group) {
  return teams
    .filter((t) => t.group === group)
    .sort((a, b) => {
      if (pts(b) !== pts(a)) return pts(b) - pts(a);
      if (goalDiff(b) !== goalDiff(a)) return goalDiff(b) - goalDiff(a);
      return b.gf - a.gf;
    });
}

// ---- Venues -----------------------------------------------------------
export const venues = [
  { city: "New York / NJ", venue: "MetLife Stadium" },
  { city: "Los Angeles", venue: "SoFi Stadium" },
  { city: "Dallas", venue: "AT&T Stadium" },
  { city: "Mexico City", venue: "Estadio Azteca" },
  { city: "Toronto", venue: "BMO Field" },
  { city: "Miami", venue: "Hard Rock Stadium" },
  { city: "Atlanta", venue: "Mercedes-Benz Stadium" },
  { city: "Vancouver", venue: "BC Place" },
  { city: "Guadalajara", venue: "Estadio Akron" },
  { city: "Seattle", venue: "Lumen Field" },
];

// ---- Matches ----------------------------------------------------------
export const matches = [
  // Matchday 3 (finished) — a sample across groups
  {
    id: "m1",
    matchday: 3,
    date: "2026-06-24T19:00:00Z",
    group: "A",
    stage: "Group Stage",
    homeId: "mex",
    awayId: "gha",
    homeScore: 3,
    awayScore: 0,
    status: "finished",
    venue: "Estadio Azteca",
    city: "Mexico City",
  },
  {
    id: "m2",
    matchday: 3,
    date: "2026-06-24T22:00:00Z",
    group: "A",
    stage: "Group Stage",
    homeId: "ned",
    awayId: "kor",
    homeScore: 2,
    awayScore: 1,
    status: "finished",
    venue: "MetLife Stadium",
    city: "New York / NJ",
  },
  {
    id: "m3",
    matchday: 3,
    date: "2026-06-25T19:00:00Z",
    group: "C",
    stage: "Group Stage",
    homeId: "usa",
    awayId: "uzb",
    homeScore: 3,
    awayScore: 1,
    status: "finished",
    venue: "SoFi Stadium",
    city: "Los Angeles",
  },
  {
    id: "m4",
    matchday: 3,
    date: "2026-06-25T22:00:00Z",
    group: "D",
    stage: "Group Stage",
    homeId: "arg",
    awayId: "sau",
    homeScore: 4,
    awayScore: 0,
    status: "finished",
    venue: "AT&T Stadium",
    city: "Dallas",
  },

  // Live now
  {
    id: "m5",
    matchday: 1,
    date: "2026-06-26T19:00:00Z",
    group: "—",
    stage: "Round of 32",
    homeId: "esp",
    awayId: "uru",
    homeScore: 1,
    awayScore: 0,
    status: "live",
    minute: 63,
    venue: "Hard Rock Stadium",
    city: "Miami",
  },
  {
    id: "m6",
    matchday: 1,
    date: "2026-06-26T19:00:00Z",
    group: "—",
    stage: "Round of 32",
    homeId: "fra",
    awayId: "ivc",
    homeScore: 2,
    awayScore: 2,
    status: "live",
    minute: 71,
    venue: "Mercedes-Benz Stadium",
    city: "Atlanta",
  },

  // Upcoming knockout fixtures
  {
    id: "m7",
    matchday: 1,
    date: "2026-06-27T19:00:00Z",
    group: "—",
    stage: "Round of 32",
    homeId: "arg",
    awayId: "cmr",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    venue: "Estadio Azteca",
    city: "Mexico City",
  },
  {
    id: "m8",
    matchday: 1,
    date: "2026-06-27T22:00:00Z",
    group: "—",
    stage: "Round of 32",
    homeId: "eng",
    awayId: "per",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    venue: "BMO Field",
    city: "Toronto",
  },
  {
    id: "m9",
    matchday: 1,
    date: "2026-06-28T19:00:00Z",
    group: "—",
    stage: "Round of 32",
    homeId: "bra",
    awayId: "alg",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    venue: "Lumen Field",
    city: "Seattle",
  },
  {
    id: "m10",
    matchday: 1,
    date: "2026-06-28T22:00:00Z",
    group: "—",
    stage: "Round of 32",
    homeId: "ger",
    awayId: "ecu",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    venue: "BC Place",
    city: "Vancouver",
  },
  {
    id: "m11",
    matchday: 1,
    date: "2026-06-29T19:00:00Z",
    group: "—",
    stage: "Round of 32",
    homeId: "por",
    awayId: "sui",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    venue: "Estadio Akron",
    city: "Guadalajara",
  },
  {
    id: "m12",
    matchday: 1,
    date: "2026-06-29T22:00:00Z",
    group: "—",
    stage: "Round of 32",
    homeId: "ned",
    awayId: "den",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    venue: "MetLife Stadium",
    city: "New York / NJ",
  },
];

// ---- Top scorers / players -------------------------------------------
export const players = [
  {
    id: "p1",
    name: "Lionel Messi",
    teamId: "arg",
    position: "FW",
    number: 10,
    age: 38,
    club: "Inter Miami",
    goals: 5,
    assists: 3,
  },
  {
    id: "p2",
    name: "Kylian Mbappé",
    teamId: "fra",
    position: "FW",
    number: 10,
    age: 27,
    club: "Real Madrid",
    goals: 5,
    assists: 1,
  },
  {
    id: "p3",
    name: "Harry Kane",
    teamId: "eng",
    position: "FW",
    number: 9,
    age: 32,
    club: "Bayern Munich",
    goals: 4,
    assists: 2,
  },
  {
    id: "p4",
    name: "Vinícius Júnior",
    teamId: "bra",
    position: "FW",
    number: 7,
    age: 25,
    club: "Real Madrid",
    goals: 4,
    assists: 3,
  },
  {
    id: "p5",
    name: "Christian Pulisic",
    teamId: "usa",
    position: "FW",
    number: 10,
    age: 27,
    club: "AC Milan",
    goals: 4,
    assists: 2,
  },
  {
    id: "p6",
    name: "Lamine Yamal",
    teamId: "esp",
    position: "FW",
    number: 19,
    age: 18,
    club: "Barcelona",
    goals: 3,
    assists: 4,
  },
  {
    id: "p7",
    name: "Cristiano Ronaldo",
    teamId: "por",
    position: "FW",
    number: 7,
    age: 41,
    club: "Al Nassr",
    goals: 3,
    assists: 1,
  },
  {
    id: "p8",
    name: "Jamal Musiala",
    teamId: "ger",
    position: "MF",
    number: 10,
    age: 23,
    club: "Bayern Munich",
    goals: 3,
    assists: 2,
  },
  {
    id: "p9",
    name: "Hirving Lozano",
    teamId: "mex",
    position: "FW",
    number: 22,
    age: 30,
    club: "San Diego FC",
    goals: 3,
    assists: 1,
  },
  {
    id: "p10",
    name: "Alphonso Davies",
    teamId: "can",
    position: "DF",
    number: 19,
    age: 25,
    club: "Bayern Munich",
    goals: 2,
    assists: 3,
  },
  {
    id: "p11",
    name: "Achraf Hakimi",
    teamId: "mar",
    position: "DF",
    number: 2,
    age: 27,
    club: "Paris SG",
    goals: 2,
    assists: 2,
  },
  {
    id: "p12",
    name: "Sadio Mané",
    teamId: "sen",
    position: "FW",
    number: 10,
    age: 34,
    club: "Al Nassr",
    goals: 3,
    assists: 0,
  },
];

export function playersForTeam(teamId) {
  return players.filter((p) => p.teamId === teamId);
}

export const topScorers = [...players].sort(
  (a, b) => b.goals - a.goals || b.assists - a.assists,
);

// ---- Knockout bracket -------------------------------------------------

export const bracket = {
  round32: [
    {
      id: "r32-1",
      homeId: "esp",
      awayId: "uru",
      homeScore: null,
      awayScore: null,
      label: "R32 · 1",
    },
    {
      id: "r32-2",
      homeId: "fra",
      awayId: "ivc",
      homeScore: null,
      awayScore: null,
      label: "R32 · 2",
    },
    {
      id: "r32-3",
      homeId: "arg",
      awayId: "cmr",
      homeScore: null,
      awayScore: null,
      label: "R32 · 3",
    },
    {
      id: "r32-4",
      homeId: "eng",
      awayId: "per",
      homeScore: null,
      awayScore: null,
      label: "R32 · 4",
    },
    {
      id: "r32-5",
      homeId: "bra",
      awayId: "alg",
      homeScore: null,
      awayScore: null,
      label: "R32 · 5",
    },
    {
      id: "r32-6",
      homeId: "ger",
      awayId: "ecu",
      homeScore: null,
      awayScore: null,
      label: "R32 · 6",
    },
    {
      id: "r32-7",
      homeId: "por",
      awayId: "sui",
      homeScore: null,
      awayScore: null,
      label: "R32 · 7",
    },
    {
      id: "r32-8",
      homeId: "ned",
      awayId: "den",
      homeScore: null,
      awayScore: null,
      label: "R32 · 8",
    },
  ],
  round16: [
    {
      id: "r16-1",
      homeId: "esp",
      awayId: "fra",
      homeScore: null,
      awayScore: null,
      label: "R16 · 1",
    },
    {
      id: "r16-2",
      homeId: "arg",
      awayId: "eng",
      homeScore: null,
      awayScore: null,
      label: "R16 · 2",
    },
    {
      id: "r16-3",
      homeId: "bra",
      awayId: "ger",
      homeScore: null,
      awayScore: null,
      label: "R16 · 3",
    },
    {
      id: "r16-4",
      homeId: "por",
      awayId: "ned",
      homeScore: null,
      awayScore: null,
      label: "R16 · 4",
    },
  ],
  quarter: [
    {
      id: "qf-1",
      homeId: "esp",
      awayId: "arg",
      homeScore: null,
      awayScore: null,
      label: "QF · 1",
    },
    {
      id: "qf-2",
      homeId: "bra",
      awayId: "por",
      homeScore: null,
      awayScore: null,
      label: "QF · 2",
    },
  ],
  semi: [
    {
      id: "sf-1",
      homeId: "arg",
      awayId: "bra",
      homeScore: null,
      awayScore: null,
      label: "Semi-final",
    },
  ],
  final: [
    {
      id: "f-1",
      homeId: null,
      awayId: null,
      homeScore: null,
      awayScore: null,
      label: "Final",
    },
  ],
};

// ---- Tournament meta --------------------------------------------------
export const tournament = {
  name: "FIFA World Cup 2026",
  hosts: "USA · Canada · Mexico",
  teamsCount: 48,
  matchesCount: 104,
  venuesCount: 16,
  daysToFinal: 18,
};
